language: rust
dist: trusty
cache: cargo
sudo: true

services:
  - docker

rust:
  - stable

before_install:
  - sudo apt-get update

matrix:
  allow_failures:
    - rust: stable

install:
  - docker build .

before_script:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - heroku container:login
  - heroku container:push web --app home-wormhole
  - heroku container:release web --app home-wormhole
