language: rust
dist: trusty
cache: cargo
sudo: true

services:
  - docker

rust:
  - stable

before_install:
  - sudo apt-get update

matrix:
  allow_failures:
    - rust: stable

addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt

install:
  - docker build .

script:
  - heroku login:container
  - heroku container:push web --app home-wormhole
  - heroku container:release web --app home-wormhole
